name: "EnvGuardian"
description: "Validate .env files against a schema"
author: "saarors"

inputs:
  schema:
    description: "Path to schema file"
    required: true
  env:
    description: "Env files (space separated)"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
